name: build
on: push
jobs:

  eloquent:
    runs-on: ubuntu-18.04
    container:
      image: docker://ros:eloquent-ros-base-bionic
    steps:
    - name: deps
      run: |
        sudo apt update && sudo apt install \
          git wget \
          python-rosdep \
          python3-vcstool \
          python3-colcon-common-extensions -y
    - name: workspace
      shell: bash
      run: |
        mkdir -p /home/ff_ws/src
        cd /home/ff_ws
        wget https://raw.githubusercontent.com/osrf/free_fleet/${GITHUB_REF:11}/free_fleet.repos
        vcs import src < free_fleet.repos
    - name: checkout
      shell: bash
      run: |
        cd /home/ff_ws/src/free_fleet
        git checkout "${GITHUB_REF:11}"
    - name: rosdeps
      shell: bash
      run: |
        cd /home/ff_ws
        rosdep update
        source /opt/ros/eloquent/setup.bash
        rosdep install --from-paths src --ignore-src -yr
    - name: build
      shell: bash
      run: |
        cd /home/ff_ws
        source /opt/ros/eloquent/setup.bash
        colcon build --packages-up-to \
          free_fleet \
          free_fleet_server \
          free_fleet_examples 
